data:
  trainDataPath: './data/train.txt'
  validDataPath: './data/valid.txt'
  modelSavePath: '../ner_params/ccfParams.pkl'
  testDataPath: './data/test.txt'
  testLenPath: './data/test.record'
  submitDataPath: './data/submit.csv'
model:
  batchSize: 30
  bert_base_chinese: '../bert_base_chinese'
  learningRate: 0.0005
  maxWordLen: 320 #与Bert对齐，不能改变
  epochNum: 100
  earlyStop: 10 #早停机制
  dropout: 0.5
