data:
  trainDataPath: './data/train.txt'
  validDataPath: './data/valid.txt'
  testDataPath: './data/test.txt'
  testLenPath: './data/test.record'
  validLenPath: './data/valid.record'

  BiLSTMCRFSavePath: '../ner_params/ccf_bilstmcrf.pkl'
  TransformerCNNSavePath: '../ner_params/ccf_transformercnn.pkl'
  BiLSTMCRFSubmitDataPath: './data/bilstmcrf_submit.csv'
  TransformerCNNSubmitDataPath: './data/transformercnn_submit.csv'


model:
  batchSize: 10
  bert_base_chinese: '../chinese_wwm_ext_pytorch'
  learningRate: 0.0001
  maxWordLen: 300 #与Bert对齐，不能改变
  hiddenSize: 400
  featureLen: 5
  epochNum: 100
  earlyStop: 8 #早停机制
  embeddingDropout: 0.5
  lstmDropout: 0.5
  dropout: 0.5
