data:
  testDataPath: './data/test.txt'
  testLenPath: './data/test.len'
  
model:
  batchSize: 10
  pretrained_model: 'Bert'
  bert_base_chinese: '../bert-base-chinese'
  xlnet_base_chinese: '../xlnet_base_chinese'
  learningRate: 0.0001
  maxWordLen: 256 #与Bert对齐，不能改变
  hiddenSize: 768
  windowSize: 5
  epochNum: 5
  earlyStop: 2 #早停机制
  dropout: 0.2
